# Generated by Django 6.0.7 on 2026-07-24 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bayram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('turi', models.CharField(choices=[('milliy', 'Milliy/qonuniy bayram'), ('diniy', 'Diniy bayram (oy taqvimi, har yili siljiydi)')], max_length=6)),
                ('oy', models.PositiveSmallIntegerField(blank=True, help_text='Faqat milliy bayramlar uchun (1-12)', null=True)),
                ('kun', models.PositiveSmallIntegerField(blank=True, help_text='Faqat milliy bayramlar uchun (1-31)', null=True)),
                ('rasman_dam_olish_kuni', models.BooleanField(default=True, help_text="False bo'lsa -- nishonlanadi, lekin ish kuni (masalan Vatan himoyachilari kuni)")),
                ('tavsif', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Bayram',
                'verbose_name_plural': 'Bayramlar',
                'db_table': 'bayramlar',
                'ordering': ['oy', 'kun'],
            },
        ),
        migrations.CreateModel(
            name='Tuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL uchun, masalan 'oltinkol-tumani'", max_length=120, unique=True)),
                ('soato_code', models.CharField(blank=True, help_text="Davlat statistika qo'mitasi SOATO/MHOBT kodi. Ba'zi yangi tumanlar uchun manbada kod buzilgan bo'lgani sabab null.", max_length=12, null=True, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('turi', models.CharField(choices=[('tuman', 'Tuman'), ('shahar', "Shahar (viloyat bo'ysunuvidagi)")], max_length=6)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'db_table': 'tumanlar',
                'ordering': ['viloyat', 'name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Valyuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu_id', models.PositiveSmallIntegerField(help_text='CBU tizimidagi ichki id', unique=True)),
                ('iso_numeric_code', models.CharField(help_text='ISO 4217 raqamli kod, masalan 840=USD', max_length=3)),
                ('code', models.CharField(db_index=True, help_text='3 harfli kod, masalan USD', max_length=3, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('nominal', models.PositiveSmallIntegerField(default=1, help_text='Kurs shuncha birlik uchun beriladi (masalan VND uchun 10)')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
                'db_table': 'valyutalar',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Viloyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 3166-2:UZ kodi, masalan UZ-TK', max_length=5, unique=True)),
                ('soato_code', models.CharField(blank=True, help_text="Davlat statistika qo'mitasi rasmiy SOATO/MHOBT kodi", max_length=10, null=True, unique=True)),
                ('name_uz', models.CharField(max_length=100)),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('center', models.CharField(blank=True, help_text='Markaz shahri', max_length=100)),
                ('turi', models.CharField(choices=[('viloyat', 'Viloyat'), ('respublika', 'Respublika'), ('shahar', 'Shahar')], default='viloyat', max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, help_text="Markaz shahrining kengligi -- namoz vaqti va shunga o'xshash hisob-kitoblar uchun", max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, help_text='Markaz shahrining uzunligi', max_digits=8, null=True)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'db_table': 'viloyatlar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='AholiPunkti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('soato_code', models.CharField(max_length=12, unique=True)),
                ('name_uz', models.CharField(max_length=150)),
                ('name_uz_cyrl', models.CharField(blank=True, max_length=150)),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aholi_punktlari', to='geo.tuman')),
            ],
            options={
                'verbose_name': 'Aholi punkti',
                'verbose_name_plural': 'Aholi punktlari',
                'db_table': 'aholi_punktlari',
                'ordering': ['tuman', 'name_uz'],
            },
        ),
        migrations.AddField(
            model_name='tuman',
            name='viloyat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tumanlar', to='geo.viloyat'),
        ),
        migrations.CreateModel(
            name='TelefonKodi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodi', models.CharField(db_index=True, max_length=3)),
                ('turi', models.CharField(choices=[('mintaqaviy', 'Mintaqaviy (simli aloqa)'), ('mobil', 'Mobil operator')], max_length=10)),
                ('operator_nomi', models.CharField(blank=True, help_text='Faqat turi=mobil uchun', max_length=50)),
                ('viloyat', models.ForeignKey(blank=True, help_text='Faqat turi=mintaqaviy uchun', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telefon_kodlari', to='geo.viloyat')),
            ],
            options={
                'verbose_name': 'Telefon kodi',
                'verbose_name_plural': 'Telefon kodlari',
                'db_table': 'telefon_kodlari',
                'ordering': ['turi', 'kodi'],
            },
        ),
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name_uz', models.CharField(max_length=300)),
                ('turi', models.CharField(choices=[('davlat', 'Davlat OTM'), ('xususiy', 'Xususiy OTM'), ('xorijiy', 'Xorijiy OTM filiali')], default='davlat', max_length=8)),
                ('source_url', models.URLField(blank=True)),
                ('viloyat', models.ForeignKey(blank=True, help_text='TAXMINIY -- nomdan avtomatik aniqlangan, tasdiqlanmagan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='otmlar', to='geo.viloyat')),
            ],
            options={
                'verbose_name': 'OTM',
                'verbose_name_plural': 'OTMlar',
                'db_table': 'otmlar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name_uz', models.CharField(max_length=200)),
                ('turi', models.CharField(choices=[('davlat', 'Davlat banki'), ('aksiyadorlik', 'Aksiyadorlik tijorat banki'), ('xususiy', 'Xususiy bank'), ('xorijiy', 'Chet el kapitali ishtirokidagi bank')], max_length=14)),
                ('address', models.CharField(help_text='Bosh ofis manzili (xom matn)', max_length=300)),
                ('license_number', models.CharField(blank=True, max_length=10)),
                ('website', models.URLField(blank=True)),
                ('viloyat', models.ForeignKey(blank=True, help_text='Bosh ofis joylashgan viloyat', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banklar', to='geo.viloyat')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banklar',
                'db_table': 'banklar',
                'ordering': ['name_uz'],
            },
        ),
        migrations.CreateModel(
            name='BayramSanasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField(db_index=True)),
                ('sana', models.DateField()),
                ('sabab', models.CharField(choices=[('asosiy', 'Asosiy kun'), ('kochirilgan', "MK 208-modda: dam kuniga to'g'ri kelgani uchun ko'chirilgan"), ('qoshimcha', "Prezident farmoni asosida qo'shimcha")], default='asosiy', max_length=12)),
                ('taxminiymi', models.BooleanField(default=False, help_text='Diniy bayramlar uchun True')),
                ('izoh', models.CharField(blank=True, max_length=200)),
                ('bayram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanalar', to='geo.bayram')),
            ],
            options={
                'verbose_name': 'Bayram sanasi',
                'verbose_name_plural': 'Bayram sanalari',
                'db_table': 'bayram_sanalari',
                'ordering': ['sana'],
                'constraints': [models.UniqueConstraint(fields=('bayram', 'sana'), name='uniq_bayram_sana')],
            },
        ),
        migrations.CreateModel(
            name='ValyutaKursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(db_index=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text="1 (yoki nominal) birlik = shuncha so'm", max_digits=12)),
                ('diff', models.DecimalField(decimal_places=2, default=0, help_text='Oldingi kunga nisbatan farq', max_digits=10)),
                ('valyuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurslar', to='geo.valyuta')),
            ],
            options={
                'verbose_name': 'Valyuta kursi',
                'verbose_name_plural': 'Valyuta kurslari',
                'db_table': 'valyuta_kurslari',
                'ordering': ['-sana', 'valyuta__code'],
                'constraints': [models.UniqueConstraint(fields=('valyuta', 'sana'), name='uniq_kurs_per_kun')],
            },
        ),
        migrations.AddConstraint(
            model_name='tuman',
            constraint=models.UniqueConstraint(fields=('viloyat', 'name_uz'), name='uniq_tuman_per_viloyat'),
        ),
        migrations.AddConstraint(
            model_name='telefonkodi',
            constraint=models.UniqueConstraint(fields=('kodi', 'operator_nomi'), name='uniq_kod_operator'),
        ),
    ]
